пр для задания
tester-dono/fun_number_fact_task pull request #1
Opened 2022-04-22 15:16 UTC by tester-dono

# Демонстрация работы
https://user-images.githubusercontent.com/47796424/164743817-58ad0744-5e3d-402c-bb2f-88409cdd7eac.mov

2022-04-24 13:26 UTC, plastb1r requested changes

2022-04-24 13:26 UTC, plastb1r commented on lib/domain/quiz.dart
> +// {
Понимаю, для удобства на базом проекте можно эту инфу положить рядом, но лучше привыкать держать файлы проекта в чистоте

2022-04-24 13:26 UTC, plastb1r commented on lib/service/repository/number_screen_rep.dart
> +      return Future.value(futureNumberFact);
ненужная обертка Future.value

2022-04-24 13:26 UTC, plastb1r commented on lib/service/repository/number_screen_rep.dart
> +      return Future.value(futureNumberFact);
ненужная обертка Future.value

2022-04-24 13:26 UTC, plastb1r commented on lib/service/repository/number_screen_rep.dart
> +          jsonDecode(responseValue.body).cast<Map<String, dynamic>>();
Map<String,Object?> - dynamic избегаем

2022-04-24 13:26 UTC, plastb1r commented on lib/service/repository/number_screen_rep.dart
> +          jsonDecode(responseValue.body).cast<Map<String, dynamic>>();
Map<String,Object?> - dynamic избегаем

2022-04-24 13:26 UTC, plastb1r commented on lib/domain/serverAnswer.dart
> +class ServerAnswer {
Можно поменять название, тк эту модель мы используем чисто на ui, и поэтому "ответ от сервера" - не лучшее название.
Что-то вроде NumberInfo

2022-04-24 13:26 UTC, plastb1r commented on lib/domain/serverAnswer.dart
> +class ServerAnswer {
Можно поменять название, тк эту модель мы используем чисто на ui, и поэтому "ответ от сервера" - не лучшее название.
Что-то вроде NumberInfo

2022-04-24 13:26 UTC, plastb1r commented on lib/ui/screen/number_screen_model.dart
> +  Future<ServerAnswer> getServerAnswer(int number) async {
И тут название тогда поменять

2022-04-24 13:26 UTC, plastb1r commented on lib/ui/screen/number_screen_model.dart
> +  Future<ServerAnswer> getServerAnswer(int number) async {
И тут название тогда поменять

2022-04-24 13:26 UTC, plastb1r commented on lib/ui/screen/number_screen_model.dart
> +  Future<String> getFact(int number) async {
Если методы не вызываются в вм`ке, то можно их сделать приватными. А в целом, вообще их убрать, и сделать прямой вызов в объединяющем методе в конце класса. Типа тут всего лишь проксирование из репы в одну строку

2022-04-24 13:26 UTC, plastb1r commented on lib/ui/screen/number_screen_model.dart
> +  Future<String> getFact(int number) async {
Если методы не вызываются в вм`ке, то можно их сделать приватными. А в целом, вообще их убрать, и сделать прямой вызов в объединяющем методе в конце класса. Типа тут всего лишь проксирование из репы в одну строку

2022-04-24 13:26 UTC, plastb1r commented on lib/domain/quiz.dart
> +class Category2 {
не понял как/где Category2 используется.
И название прикольное))0)

2022-04-24 13:26 UTC, plastb1r commented on lib/domain/quiz.dart
> +class Category2 {
не понял как/где Category2 используется.
И название прикольное))0)

2022-04-24 13:26 UTC, plastb1r commented on lib/ui/screen/number_screen_model.dart
> +  /// на самом деле я подумал о том, что можно сделать что то вроде
То что ты описываешь свои мысли - показываешь почему сделал так, а не иначе - круто, но лучше их вести в самом пр`е, ссылаясь на куски кода. Ведь тут должен находиться конечный результат обсуждений, а не само обсуждение

2022-04-24 13:26 UTC, plastb1r commented on lib/ui/screen/number_screen_model.dart
> +  /// на самом деле я подумал о том, что можно сделать что то вроде
То что ты описываешь свои мысли - показываешь почему сделал так, а не иначе - круто, но лучше их вести в самом пр`е, ссылаясь на куски кода. Ведь тут должен находиться конечный результат обсуждений, а не само обсуждение

2022-04-25 07:54 UTC, tester-dono commented on lib/domain/quiz.dart
> +// {
я просто подумал, что сваггера в задании не было, да и созвать его избыточно, а так хотя бы видно что за запрос

2022-04-25 07:54 UTC, tester-dono commented on lib/domain/quiz.dart
> +// {
если что удалил

2022-04-25 08:14 UTC, tester-dono commented on lib/service/repository/number_screen_rep.dart
> +          jsonDecode(responseValue.body).cast<Map<String, dynamic>>();
ok, я просто подумал, раз это в официальной вики да еще и только для парсинга, то можно и динамик запихнуть

2022-04-25 08:18 UTC, tester-dono commented on lib/ui/screen/number_screen_model.dart
> +  Future<String> getFact(int number) async {
ну с одной стороны я тоже об этом думал, что это избыточно и не нужно, но вдруг мы бы начали изменять полученный ответ с репозитория и все такое

2022-04-25 08:19 UTC, tester-dono commented on lib/ui/screen/number_screen_model.dart
> +  Future<String> getFact(int number) async {
в общем убрал

2022-04-25 08:20 UTC, tester-dono commented on lib/domain/quiz.dart
> +class Category2 {
))))))

2022-04-25 08:21 UTC, tester-dono commented on lib/domain/quiz.dart
> +class Category2 {
категория это класс в quiz, используется путем вызова поля id из категории и отображением его на ui

2022-04-25 08:22 UTC, tester-dono commented on lib/domain/quiz.dart
> +class Category2 {
хотя да название мемное, сейчас переименую

2022-04-25 08:24 UTC, tester-dono commented on lib/ui/screen/number_screen_model.dart
> +  /// на самом деле я подумал о том, что можно сделать что то вроде
ok, просто привычка сначала комментировать моменты, чтобы не забыть, а потом на пр обсуждать и стирать

2022-04-28 14:24 UTC, plastb1r approved these changes

2022-05-04 14:11 UTC, merged